
# Test arithmetique

fara
  naɗa lambar1 = 25 
  naɗa lambar2 = 10
  naɗa jimila = lambar1 + lambar2

  rubuta "=== Lambar1 + Lambar2 ==="
  rubuta "Jimila = "
  rubuta jimila


  # Test substraction
  naɗa ragi = lambar1 - lambar2
  rubuta "=== Lambar1 - Lambar2 ==="
  rubuta ragi

  # Test Ninka
  naɗa ninka = lambar1 * lambar2
  rubuta "=== Lambar1 * Lambar2 ==="
  rubuta ninka

  # Test Division
  naɗa divi = lambar1 / lambar2
  rubuta "=== Lambar1 / Lambar2 ==="
  rubuta divi
ƙare